import React, { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";

export type Locale = "en" | "ar" | "fr" | "zh";

type Dictionary = Record<string, string>;

const ar: Dictionary = {
  Home: "الرئيسية", Services: "الخدمات", Projects: "المشاريع", Partners: "الشركاء", About: "من نحن", Blog: "الأخبار", Contact: "تواصل معنا",
  "Plan your event": "خطط لفعاليتك", "Talk to Litigon": "تحدث مع ليتغون", "Pages": "الصفحات", "Head Office:": "المكتب الرئيسي:",
  "Riyadh, Kingdom of Saudi Arabia": "الرياض، المملكة العربية السعودية", "All rights reserved.": "جميع الحقوق محفوظة.", "Privacy Policy": "سياسة الخصوصية", "Terms & Conditions": "الشروط والأحكام",
  "Events & Conferences Management": "إدارة الفعاليات والمؤتمرات", "We Create Exceptional Impact": "نصنع تأثيراً استثنائياً",
  "See our work": "شاهد أعمالنا", "An integrated ecosystem": "منظومة متكاملة",
  "Strategy, creativity, production and logistics under one roof — so nothing falls between suppliers.": "الاستراتيجية والإبداع والإنتاج والخدمات اللوجستية تحت سقف واحد لضمان تكامل كل التفاصيل.",
  "Featured projects": "مشاريع مختارة", "All projects": "جميع المشاريع", "How we work": "كيف نعمل", Strategy: "الاستراتيجية", Creative: "الإبداع", Production: "الإنتاج", Operations: "العمليات",
  "Company updates & press releases": "أخبار الشركة والبيانات الصحفية", Newsroom: "غرفة الأخبار", "All updates": "جميع الأخبار",
  "Announcements, project stories and news from our events, shows and exhibitions across Saudi Arabia.": "إعلانات وقصص مشاريع وأخبار من فعالياتنا وعروضنا ومعارضنا في أنحاء المملكة العربية السعودية.",
  "Ready to plan your next event?": "هل أنت مستعد لتخطيط فعاليتك القادمة؟", "Tell us the date, the audience and the ambition — we will handle the rest.": "أخبرنا بالموعد والجمهور والطموح، وسنتولى نحن الباقي.",
  "Our services": "خدماتنا", "Everything an event needs, in one team": "كل ما تحتاجه الفعالية ضمن فريق واحد", "Our capabilities": "قدراتنا", "Moments we engineer": "لحظات نصنعها بإتقان",
  "Litigon covers strategy, creative direction, technical production, hospitality and operations — so your event has a single point of accountability.": "تجمع ليتغون الاستراتيجية والتوجيه الإبداعي والإنتاج التقني والضيافة والعمليات، لتكون فعاليتك تحت مسؤولية فريق واحد.",
  "Nine core services, delivered by our own teams and trusted specialists.": "تسع خدمات أساسية تقدمها فرقنا ومتخصصون موثوقون.",
  "Technology, spectacle and hospitality combined into experiences guests remember long after the last guest leaves.": "نجمع التقنية والإبهار والضيافة لنصنع تجارب تبقى في ذاكرة الضيوف طويلاً.",
  "Drone shows": "عروض الدرون", "Fireworks & pyrotechnics": "الألعاب النارية والمؤثرات", "AI technologies": "تقنيات الذكاء الاصطناعي", "Conferences & summits": "المؤتمرات والقمم", "VIP reception": "استقبال كبار الشخصيات", "Private aviation": "الطيران الخاص",
  "Events & Conference Management": "إدارة الفعاليات والمؤتمرات", "Strategic Conferences & Summits": "المؤتمرات والقمم الاستراتيجية", "AI & Smart Experiences": "الذكاء الاصطناعي والتجارب الذكية", "Marketing Management": "إدارة التسويق", "Entertainment & Cultural Seasons": "الترفيه والمواسم الثقافية", "Crowd Management": "إدارة الحشود", "VIP & Official Delegations": "كبار الشخصيات والوفود الرسمية", "Show Production": "إنتاج العروض",
  "Our work": "أعمالنا", "Projects delivered across the Kingdom": "مشاريع نُفذت في أنحاء المملكة", "Success Partners": "شركاء النجاح", "Trusted by leading organizations": "موثوقون لدى مؤسسات رائدة", "Become a partner": "كن شريكاً لنا",
  "A selection of conferences, exhibitions, sports weekends and public celebrations produced by the Litigon team.": "مجموعة مختارة من المؤتمرات والمعارض والفعاليات الرياضية والاحتفالات العامة التي أنتجها فريق ليتغون.",
  "We are proud to work alongside government entities, corporations and institutions that share our commitment to exceptional events and experiences.": "نفخر بالعمل مع الجهات الحكومية والشركات والمؤسسات التي تشاركنا الالتزام بتقديم فعاليات وتجارب استثنائية.",
  "Interested in collaborating with Litigon? We work with brands, venues, technology providers and public entities to deliver standout events across the Kingdom.": "هل ترغب في التعاون مع ليتغون؟ نعمل مع العلامات التجارية والمواقع ومزودي التقنية والجهات العامة لتقديم فعاليات مميزة في أنحاء المملكة.",
  "About us": "من نحن", "We create exceptional impact": "نصنع تأثيراً استثنائياً", Vision: "الرؤية", Mission: "الرسالة", "Our foundations": "مرتكزاتنا", "Litigon in numbers": "ليتغون بالأرقام", "Scale, measured in delivery": "حجمنا تقيسه إنجازاتنا", "Scope of services": "نطاق الخدمات", "Explore our services": "استكشف خدماتنا",
  "Integrated Ecosystem": "منظومة متكاملة", "Innovation in Experience": "الابتكار في التجربة", "Operational Excellence": "التميز التشغيلي", "Strategic Reliability": "الموثوقية الاستراتيجية",
  "Events & conferences management": "إدارة الفعاليات والمؤتمرات", "Serving clients across Saudi Arabia.": "نخدم عملاءنا في جميع أنحاء المملكة العربية السعودية.", "Let’s plan your next event": "لنخطط لفعاليتك القادمة",
  "Contact us": "تواصل معنا", "Tell us about your event": "حدثنا عن فعاليتك", "First Name": "الاسم الأول", "Last Name": "اسم العائلة", Email: "البريد الإلكتروني", Phone: "الهاتف", Subject: "الموضوع", Message: "الرسالة", "Type Message": "اكتب رسالتك", "Send a Message": "إرسال الرسالة",
  "Share the date, the audience and the ambition — our team will get back to you within one business day.": "شاركنا الموعد والجمهور والطموح، وسيتواصل معك فريقنا خلال يوم عمل واحد.", "Your Email": "بريدك الإلكتروني", "Message sent successfully!": "تم إرسال الرسالة بنجاح!", "We'll get back to you as soon as possible.": "سنتواصل معك في أقرب وقت ممكن.",
  "Direct contact": "تواصل مباشر", "Choose the channel that works best for you. We usually respond within one business day.": "اختر وسيلة التواصل الأنسب لك. نرد عادةً خلال يوم عمل واحد.", "Follow Litigon": "تابع ليتغون", "Event enquiry": "استفسار عن فعالية", "Share the essentials below and we’ll come back with the right next step.": "شاركنا المعلومات الأساسية أدناه وسنعود إليك بالخطوة المناسبة التالية.", "(Optional)": "(اختياري)", "There is a problem with your submission.": "توجد مشكلة في البيانات المرسلة.", "Please review the highlighted fields and try again.": "يرجى مراجعة الحقول المحددة والمحاولة مرة أخرى.", "Sending...": "جارٍ الإرسال...", "Your information is only used to respond to this enquiry.": "تُستخدم معلوماتك فقط للرد على هذا الاستفسار.",
  FAQs: "الأسئلة الشائعة", "Frequently asked questions": "الأسئلة الأكثر شيوعاً", "Everything you need to know before we start planning together.": "كل ما تحتاج إلى معرفته قبل أن نبدأ التخطيط معاً.", "Talk to our team": "تحدث مع فريقنا",
  "What does Litigon do?": "ماذا تقدم ليتغون؟", "How early should we contact you?": "متى ينبغي التواصل معكم؟", "Do you manage the whole event or only parts of it?": "هل تديرون الفعالية كاملة أم أجزاء منها؟", "Can you handle VIPs and official delegations?": "هل تستقبلون كبار الشخصيات والوفود الرسمية؟", "Do you produce drone shows and fireworks?": "هل تنتجون عروض الدرون والألعاب النارية؟", "Where do you work?": "أين تعملون؟", "How is pricing decided?": "كيف يتم تحديد الأسعار؟", "Can you support Saudi Vision 2030 programmes?": "هل تدعمون برامج رؤية السعودية 2030؟",
  "Company updates": "أخبار الشركة", "Press releases & project stories": "بيانات صحفية وقصص مشاريع", "News from behind Saudi Arabia's biggest events": "أخبار من كواليس أكبر فعاليات السعودية", By: "بواسطة", "Back to Blog": "العودة إلى الأخبار", "More from Litigon": "المزيد من ليتغون",
  "Exhibitions & stands": "المعارض والأجنحة", "Cultural seasons": "المواسم الثقافية", "Show production": "إنتاج العروض",
  "Select language": "اختر اللغة", English: "English", Arabic: "العربية", French: "Français", Chinese: "中文", Close: "إغلاق"
};

const fr: Dictionary = {
  Home: "Accueil", Services: "Services", Projects: "Projets", Partners: "Partenaires", About: "À propos", Blog: "Actualités", Contact: "Contact",
  "Plan your event": "Planifier votre événement", "Talk to Litigon": "Parler à Litigon", Pages: "Pages", "Head Office:": "Siège social :", "Riyadh, Kingdom of Saudi Arabia": "Riyad, Royaume d’Arabie saoudite", "All rights reserved.": "Tous droits réservés.", "Privacy Policy": "Politique de confidentialité", "Terms & Conditions": "Conditions générales",
  "Events & Conferences Management": "Gestion d’événements et de conférences", "We Create Exceptional Impact": "Nous créons un impact exceptionnel", "See our work": "Découvrir nos réalisations", "An integrated ecosystem": "Un écosystème intégré",
  "Strategy, creativity, production and logistics under one roof — so nothing falls between suppliers.": "Stratégie, création, production et logistique réunies pour une exécution parfaitement coordonnée.",
  "Featured projects": "Projets à la une", "All projects": "Tous les projets", "How we work": "Notre méthode", Strategy: "Stratégie", Creative: "Création", Production: "Production", Operations: "Opérations",
  "Company updates & press releases": "Actualités et communiqués de presse", Newsroom: "Actualités", "All updates": "Toutes les actualités", "Ready to plan your next event?": "Prêt à organiser votre prochain événement ?", "Tell us the date, the audience and the ambition — we will handle the rest.": "Indiquez-nous la date, le public et votre ambition — nous nous occupons du reste.",
  "Announcements, project stories and news from our events, shows and exhibitions across Saudi Arabia.": "Annonces, récits de projets et nouvelles de nos événements, spectacles et expositions en Arabie saoudite.",
  "Our services": "Nos services", "Everything an event needs, in one team": "Tout ce dont votre événement a besoin, avec une seule équipe", "Our capabilities": "Nos expertises", "Moments we engineer": "Des moments conçus avec précision",
  "Litigon covers strategy, creative direction, technical production, hospitality and operations — so your event has a single point of accountability.": "Litigon réunit stratégie, direction créative, production technique, accueil et opérations afin qu’une seule équipe soit responsable de votre événement.", "Nine core services, delivered by our own teams and trusted specialists.": "Neuf services essentiels, assurés par nos équipes et des spécialistes de confiance.", "Technology, spectacle and hospitality combined into experiences guests remember long after the last guest leaves.": "Technologie, spectacle et hospitalité réunis dans des expériences qui restent longtemps en mémoire.",
  "Drone shows": "Spectacles de drones", "Fireworks & pyrotechnics": "Feux d’artifice et pyrotechnie", "AI technologies": "Technologies d’IA", "Conferences & summits": "Conférences et sommets", "VIP reception": "Accueil VIP", "Private aviation": "Aviation privée",
  "Events & Conference Management": "Gestion d’événements et de conférences", "Strategic Conferences & Summits": "Conférences et sommets stratégiques", "AI & Smart Experiences": "IA et expériences intelligentes", "Marketing Management": "Gestion marketing", "Entertainment & Cultural Seasons": "Divertissement et saisons culturelles", "Crowd Management": "Gestion des foules", "VIP & Official Delegations": "VIP et délégations officielles", "Show Production": "Production de spectacles",
  "Our work": "Nos réalisations", "Projects delivered across the Kingdom": "Des projets réalisés dans tout le Royaume", "Success Partners": "Partenaires de réussite", "Trusted by leading organizations": "La confiance des organisations de premier plan", "Become a partner": "Devenir partenaire",
  "A selection of conferences, exhibitions, sports weekends and public celebrations produced by the Litigon team.": "Une sélection de conférences, expositions, événements sportifs et célébrations publiques produites par l’équipe Litigon.", "We are proud to work alongside government entities, corporations and institutions that share our commitment to exceptional events and experiences.": "Nous sommes fiers de collaborer avec des organismes publics, entreprises et institutions partageant notre exigence d’expériences exceptionnelles.", "Interested in collaborating with Litigon? We work with brands, venues, technology providers and public entities to deliver standout events across the Kingdom.": "Vous souhaitez collaborer avec Litigon ? Nous travaillons avec des marques, des sites, des fournisseurs technologiques et des organismes publics dans tout le Royaume.",
  "About us": "À propos", "We create exceptional impact": "Nous créons un impact exceptionnel", Vision: "Vision", Mission: "Mission", "Our foundations": "Nos fondements", "Litigon in numbers": "Litigon en chiffres", "Scale, measured in delivery": "Une envergure mesurée par nos réalisations", "Scope of services": "Étendue des services", "Explore our services": "Découvrir nos services",
  "Integrated Ecosystem": "Écosystème intégré", "Innovation in Experience": "Innovation dans l’expérience", "Operational Excellence": "Excellence opérationnelle", "Strategic Reliability": "Fiabilité stratégique",
  "Events & conferences management": "Gestion d’événements et de conférences", "Serving clients across Saudi Arabia.": "Au service de clients dans toute l’Arabie saoudite.", "Let’s plan your next event": "Planifions votre prochain événement",
  "Contact us": "Contactez-nous", "Tell us about your event": "Parlez-nous de votre événement", "First Name": "Prénom", "Last Name": "Nom", Email: "E-mail", Phone: "Téléphone", Subject: "Objet", Message: "Message", "Type Message": "Écrivez votre message", "Send a Message": "Envoyer le message",
  "Share the date, the audience and the ambition — our team will get back to you within one business day.": "Indiquez-nous la date, le public et votre ambition — notre équipe vous répondra sous un jour ouvré.", "Your Email": "Votre e-mail", "Message sent successfully!": "Message envoyé !", "We'll get back to you as soon as possible.": "Nous vous répondrons dans les meilleurs délais.",
  "Direct contact": "Contact direct", "Choose the channel that works best for you. We usually respond within one business day.": "Choisissez le moyen de contact qui vous convient. Nous répondons généralement sous un jour ouvré.", "Follow Litigon": "Suivez Litigon", "Event enquiry": "Demande événementielle", "Share the essentials below and we’ll come back with the right next step.": "Partagez les informations essentielles ci-dessous et nous vous proposerons la prochaine étape adaptée.", "(Optional)": "(Facultatif)", "There is a problem with your submission.": "Votre envoi comporte un problème.", "Please review the highlighted fields and try again.": "Vérifiez les champs indiqués puis réessayez.", "Sending...": "Envoi en cours...", "Your information is only used to respond to this enquiry.": "Vos informations servent uniquement à répondre à cette demande.",
  FAQs: "FAQ", "Frequently asked questions": "Questions fréquentes", "Everything you need to know before we start planning together.": "Tout ce qu’il faut savoir avant de commencer à planifier ensemble.", "Talk to our team": "Parler à notre équipe",
  "What does Litigon do?": "Que fait Litigon ?", "How early should we contact you?": "Combien de temps à l’avance faut-il nous contacter ?", "Do you manage the whole event or only parts of it?": "Gérez-vous tout l’événement ou seulement certaines parties ?", "Can you handle VIPs and official delegations?": "Pouvez-vous accueillir les VIP et délégations officielles ?", "Do you produce drone shows and fireworks?": "Produisez-vous des spectacles de drones et des feux d’artifice ?", "Where do you work?": "Où intervenez-vous ?", "How is pricing decided?": "Comment les tarifs sont-ils établis ?", "Can you support Saudi Vision 2030 programmes?": "Pouvez-vous accompagner les programmes Vision 2030 ?",
  "Company updates": "Actualités de l’entreprise", "Press releases & project stories": "Communiqués et histoires de projets", "News from behind Saudi Arabia's biggest events": "Dans les coulisses des plus grands événements saoudiens", By: "Par", "Back to Blog": "Retour aux actualités", "More from Litigon": "Plus d’actualités Litigon",
  "Exhibitions & stands": "Expositions et stands", "Cultural seasons": "Saisons culturelles", "Show production": "Production de spectacles", "Select language": "Choisir la langue", English: "English", Arabic: "العربية", French: "Français", Chinese: "中文", Close: "Fermer"
};

const zh: Dictionary = {
  Home: "首页", Services: "服务", Projects: "项目", Partners: "合作伙伴", About: "关于我们", Blog: "新闻", Contact: "联系我们",
  "Plan your event": "策划您的活动", "Talk to Litigon": "联系 Litigon", Pages: "页面", "Head Office:": "总部：", "Riyadh, Kingdom of Saudi Arabia": "沙特阿拉伯王国利雅得", "All rights reserved.": "版权所有。", "Privacy Policy": "隐私政策", "Terms & Conditions": "条款与条件",
  "Events & Conferences Management": "活动与会议管理", "We Create Exceptional Impact": "我们创造非凡影响力", "See our work": "查看案例", "An integrated ecosystem": "一体化生态系统",
  "Strategy, creativity, production and logistics under one roof — so nothing falls between suppliers.": "战略、创意、制作与物流汇聚于一个团队，让每个环节无缝衔接。",
  "Featured projects": "精选项目", "All projects": "全部项目", "How we work": "我们的工作方式", Strategy: "战略", Creative: "创意", Production: "制作", Operations: "运营",
  "Company updates & press releases": "公司动态与新闻稿", Newsroom: "新闻中心", "All updates": "全部动态", "Ready to plan your next event?": "准备好策划下一场活动了吗？", "Tell us the date, the audience and the ambition — we will handle the rest.": "告诉我们日期、受众和目标，其余交给我们。",
  "Announcements, project stories and news from our events, shows and exhibitions across Saudi Arabia.": "了解我们在沙特各地的活动、演出和展览动态、项目故事及公告。",
  "Our services": "我们的服务", "Everything an event needs, in one team": "一支团队，满足活动的一切需求", "Our capabilities": "我们的能力", "Moments we engineer": "我们精心打造的难忘时刻",
  "Litigon covers strategy, creative direction, technical production, hospitality and operations — so your event has a single point of accountability.": "Litigon 涵盖战略、创意指导、技术制作、接待与运营，让一支团队对您的整场活动负责。", "Nine core services, delivered by our own teams and trusted specialists.": "九项核心服务，由自有团队和可信赖的专家提供。", "Technology, spectacle and hospitality combined into experiences guests remember long after the last guest leaves.": "融合科技、视听奇观与周到接待，打造令人久久难忘的体验。",
  "Drone shows": "无人机表演", "Fireworks & pyrotechnics": "烟花与特效", "AI technologies": "人工智能技术", "Conferences & summits": "会议与峰会", "VIP reception": "贵宾接待", "Private aviation": "私人航空",
  "Events & Conference Management": "活动与会议管理", "Strategic Conferences & Summits": "战略会议与峰会", "AI & Smart Experiences": "人工智能与智慧体验", "Marketing Management": "营销管理", "Entertainment & Cultural Seasons": "娱乐与文化季", "Crowd Management": "人群管理", "VIP & Official Delegations": "贵宾与官方代表团", "Show Production": "演出制作",
  "Our work": "我们的作品", "Projects delivered across the Kingdom": "遍布沙特王国的项目", "Success Partners": "成功合作伙伴", "Trusted by leading organizations": "深受领先机构信赖", "Become a partner": "成为合作伙伴",
  "A selection of conferences, exhibitions, sports weekends and public celebrations produced by the Litigon team.": "精选由 Litigon 团队打造的会议、展览、体育周末和公共庆典。", "We are proud to work alongside government entities, corporations and institutions that share our commitment to exceptional events and experiences.": "我们很荣幸与同样致力于卓越活动和体验的政府机构、企业及组织携手合作。", "Interested in collaborating with Litigon? We work with brands, venues, technology providers and public entities to deliver standout events across the Kingdom.": "有意与 Litigon 合作？我们携手品牌、场地、技术供应商和公共机构，在沙特各地呈现卓越活动。",
  "About us": "关于我们", "We create exceptional impact": "我们创造非凡影响力", Vision: "愿景", Mission: "使命", "Our foundations": "我们的基石", "Litigon in numbers": "数字看 Litigon", "Scale, measured in delivery": "以成果衡量规模", "Scope of services": "服务范围", "Explore our services": "探索我们的服务",
  "Integrated Ecosystem": "一体化生态系统", "Innovation in Experience": "体验创新", "Operational Excellence": "卓越运营", "Strategic Reliability": "战略可靠性",
  "Events & conferences management": "活动与会议管理", "Serving clients across Saudi Arabia.": "服务遍及沙特阿拉伯。", "Let’s plan your next event": "让我们策划您的下一场活动",
  "Contact us": "联系我们", "Tell us about your event": "介绍一下您的活动", "First Name": "名字", "Last Name": "姓氏", Email: "电子邮箱", Phone: "电话", Subject: "主题", Message: "留言", "Type Message": "输入留言", "Send a Message": "发送留言",
  "Share the date, the audience and the ambition — our team will get back to you within one business day.": "告诉我们日期、受众和目标，我们的团队将在一个工作日内回复。", "Your Email": "您的电子邮箱", "Message sent successfully!": "留言已成功发送！", "We'll get back to you as soon as possible.": "我们会尽快与您联系。",
  "Direct contact": "直接联系", "Choose the channel that works best for you. We usually respond within one business day.": "请选择最适合您的联系方式。我们通常会在一个工作日内回复。", "Follow Litigon": "关注 Litigon", "Event enquiry": "活动咨询", "Share the essentials below and we’ll come back with the right next step.": "请在下方提供关键信息，我们会为您建议合适的下一步。", "(Optional)": "(选填)", "There is a problem with your submission.": "您提交的信息存在问题。", "Please review the highlighted fields and try again.": "请检查标出的字段后重试。", "Sending...": "正在发送...", "Your information is only used to respond to this enquiry.": "您的信息仅用于回复本次咨询。",
  FAQs: "常见问题", "Frequently asked questions": "常见问题", "Everything you need to know before we start planning together.": "开始共同策划前，您需要了解的一切。", "Talk to our team": "联系我们的团队",
  "What does Litigon do?": "Litigon 提供哪些服务？", "How early should we contact you?": "应该提前多久联系我们？", "Do you manage the whole event or only parts of it?": "你们管理整场活动还是其中一部分？", "Can you handle VIPs and official delegations?": "你们能接待贵宾和官方代表团吗？", "Do you produce drone shows and fireworks?": "你们制作无人机和烟花表演吗？", "Where do you work?": "你们在哪里开展业务？", "How is pricing decided?": "价格如何确定？", "Can you support Saudi Vision 2030 programmes?": "你们能支持沙特 2030 愿景项目吗？",
  "Company updates": "公司动态", "Press releases & project stories": "新闻稿与项目故事", "News from behind Saudi Arabia's biggest events": "走进沙特大型活动幕后", By: "作者", "Back to Blog": "返回新闻", "More from Litigon": "更多 Litigon 动态",
  "Exhibitions & stands": "展览与展台", "Cultural seasons": "文化季", "Show production": "演出制作", "Select language": "选择语言", English: "English", Arabic: "العربية", French: "Français", Chinese: "中文", Close: "关闭"
};

Object.assign(ar, {
  "Serving clients across": "نخدم عملاءنا في", "Saudi Arabia": "المملكة العربية السعودية", "Riyadh,": "الرياض،",
  "Litigon designs, produces and manages conferences, exhibitions and national celebrations across the Kingdom of Saudi Arabia — from the first idea to the final firework.": "تصمم ليتغون وتنتج وتدير المؤتمرات والمعارض والاحتفالات الوطنية في أنحاء المملكة، من الفكرة الأولى حتى اللحظة الختامية.",
  "End-to-end management of conferences, exhibitions and corporate events: strategy, creative direction, production and on-site logistics.": "إدارة شاملة للمؤتمرات والمعارض وفعاليات الشركات، من الاستراتيجية والتوجيه الإبداعي إلى الإنتاج والخدمات اللوجستية.",
  "Agenda design, speaker and delegation coordination, registration and hospitality for high-level summits.": "تصميم جداول الأعمال وتنسيق المتحدثين والوفود والتسجيل والضيافة للقمم رفيعة المستوى.",
  "Interactive installations, smart registration and data-driven experiences that make every guest feel recognised.": "تجهيزات تفاعلية وتسجيل ذكي وتجارب مدعومة بالبيانات تمنح كل ضيف تجربة شخصية.",
  "Campaign planning, content production and media coverage that build attendance before the doors open.": "تخطيط الحملات وإنتاج المحتوى والتغطية الإعلامية لبناء الحضور قبل انطلاق الفعالية.",
  "Programming and operating cultural seasons, festivals and national celebrations for wide public audiences.": "برمجة وتشغيل المواسم الثقافية والمهرجانات والاحتفالات الوطنية للجمهور الواسع.",
  "Flow planning, access control and safety operations for venues of every scale.": "تخطيط حركة الزوار والتحكم بالدخول وعمليات السلامة للمواقع بمختلف أحجامها.",
  "Protocol, reception and private hospitality for ministers, sponsors and official delegations.": "مراسم واستقبال وضيافة خاصة للوزراء والرعاة والوفود الرسمية.",
  "Private Aviation": "الطيران الخاص",
  "Private jet arrangements, airport handling and ground transfers for guests and delegations.": "ترتيبات الطائرات الخاصة وخدمات المطارات والنقل الأرضي للضيوف والوفود.",
  "Drone shows, fireworks, stage design, lighting and sound engineered for one unforgettable moment.": "عروض الدرون والألعاب النارية وتصميم المسارح والإضاءة والصوت للحظات لا تُنسى.",
  "Choreographed drone formations that turn the night sky into your message.": "تشكيلات درون متناغمة تحول سماء الليل إلى رسالتك.",
  "Licensed pyrotechnic displays synchronised to music and stage moments.": "عروض ألعاب نارية مرخصة ومتزامنة مع الموسيقى ولحظات المسرح.",
  "Smart registration, crowd analytics and interactive content driven by AI.": "تسجيل ذكي وتحليلات للحشود ومحتوى تفاعلي مدعوم بالذكاء الاصطناعي.",
  "Halls, stages, translation and hospitality built for high-level agendas.": "قاعات ومسارح وترجمة وضيافة مصممة للأجندات رفيعة المستوى.",
  "Protocol-trained hosts, lounges and transport for official delegations.": "مضيفون مدربون على البروتوكول وصالات ونقل للوفود الرسمية.",
  "Private jet charters, airport handling and seamless ground transfers.": "استئجار طائرات خاصة وخدمات مطارات ونقل أرضي سلس.",
  "One team from the first brief to the final report, supporting the ambitions of Saudi Vision 2030.": "فريق واحد من موجز العمل الأول حتى التقرير النهائي، دعماً لطموحات رؤية السعودية 2030.",
  "We start with your objective, audience and budget, then shape the event concept around it.": "نبدأ بهدفك وجمهورك وميزانيتك، ثم نبني مفهوم الفعالية حولها.",
  "Identity, stage design, content and show flow developed as one visual story.": "نطور الهوية وتصميم المسرح والمحتوى وتسلسل العرض كقصة بصرية واحدة.",
  "Build, staging, lighting, sound and technology delivered by our own crews.": "تنفذ فرقنا أعمال البناء والمسارح والإضاءة والصوت والتقنية.",
  "Logistics, hospitality, crowd flow and reporting on the day and after it.": "الخدمات اللوجستية والضيافة وحركة الحشود والتقارير أثناء الفعالية وبعدها.",
  "Events and conferences management in the Kingdom of Saudi Arabia. We create exceptional impact.": "إدارة الفعاليات والمؤتمرات في المملكة العربية السعودية. نصنع تأثيراً استثنائياً.",
  "Kingdom of Saudi Arabia": "المملكة العربية السعودية",
  "Litigon was founded to redefine the events and experiences industry through integrated solutions that combine strategic thinking, creative excellence, and flawless execution. We transform ambitious visions into world-class experiences that inspire audiences, elevate brands, and reinforce Saudi Arabia's position as a global destination for events, business tourism, and entertainment.": "تأسست ليتغون لإعادة تعريف صناعة الفعاليات والتجارب عبر حلول متكاملة تجمع التفكير الاستراتيجي والإبداع والتنفيذ المتقن. نحول الرؤى الطموحة إلى تجارب عالمية تلهم الجمهور وترتقي بالعلامات التجارية وتعزز مكانة المملكة كوجهة عالمية للفعاليات والترفيه.",
  "Shaping the future of the events industry in Saudi Arabia": "نرسم مستقبل صناعة الفعاليات في المملكة العربية السعودية",
  "Turning bold ideas into unforgettable experiences": "نحول الأفكار الجريئة إلى تجارب لا تُنسى",
  "Four principles behind every Litigon delivery": "أربعة مبادئ تقود كل إنجاز في ليتغون",
  "Success partners": "شركاء النجاح", "Successful events delivered": "فعالية ناجحة تم تنفيذها", "Operational & technical management hours": "ساعة إدارة تشغيلية وتقنية", "Artists & influencers managed": "فنان ومؤثر تمت إدارتهم",
  "Planning, development, execution and operations": "التخطيط والتطوير والتنفيذ والتشغيل"
});

Object.assign(fr, {
  "Serving clients across": "Au service de clients dans toute", "Saudi Arabia": "l’Arabie saoudite", "Riyadh,": "Riyad,",
  "Litigon designs, produces and manages conferences, exhibitions and national celebrations across the Kingdom of Saudi Arabia — from the first idea to the final firework.": "Litigon conçoit, produit et gère des conférences, expositions et célébrations nationales dans toute l’Arabie saoudite, de la première idée au moment final.",
  "End-to-end management of conferences, exhibitions and corporate events: strategy, creative direction, production and on-site logistics.": "Gestion complète des conférences, expositions et événements d’entreprise : stratégie, direction créative, production et logistique sur site.",
  "Agenda design, speaker and delegation coordination, registration and hospitality for high-level summits.": "Conception des programmes, coordination des intervenants et délégations, inscriptions et accueil pour les sommets de haut niveau.",
  "Interactive installations, smart registration and data-driven experiences that make every guest feel recognised.": "Installations interactives, inscriptions intelligentes et expériences personnalisées grâce aux données.",
  "Campaign planning, content production and media coverage that build attendance before the doors open.": "Planification de campagnes, production de contenu et couverture médiatique pour mobiliser le public en amont.",
  "Programming and operating cultural seasons, festivals and national celebrations for wide public audiences.": "Programmation et exploitation de saisons culturelles, festivals et célébrations nationales grand public.",
  "Flow planning, access control and safety operations for venues of every scale.": "Planification des flux, contrôle des accès et sécurité pour des sites de toute taille.",
  "Protocol, reception and private hospitality for ministers, sponsors and official delegations.": "Protocole, accueil et hospitalité privée pour ministres, sponsors et délégations officielles.",
  "Private Aviation": "Aviation privée", "Private jet arrangements, airport handling and ground transfers for guests and delegations.": "Organisation de jets privés, assistance aéroportuaire et transferts terrestres pour les invités et délégations.",
  "Drone shows, fireworks, stage design, lighting and sound engineered for one unforgettable moment.": "Spectacles de drones, feux d’artifice, scénographie, lumière et son conçus pour un moment inoubliable.",
  "Choreographed drone formations that turn the night sky into your message.": "Des chorégraphies de drones qui transforment le ciel nocturne en message.", "Licensed pyrotechnic displays synchronised to music and stage moments.": "Des spectacles pyrotechniques autorisés, synchronisés avec la musique et la scène.", "Smart registration, crowd analytics and interactive content driven by AI.": "Inscriptions intelligentes, analyse des foules et contenus interactifs propulsés par l’IA.", "Halls, stages, translation and hospitality built for high-level agendas.": "Salles, scènes, interprétation et accueil adaptés aux programmes de haut niveau.", "Protocol-trained hosts, lounges and transport for official delegations.": "Hôtes formés au protocole, salons et transport pour les délégations officielles.", "Private jet charters, airport handling and seamless ground transfers.": "Affrètement de jets privés, assistance aéroportuaire et transferts fluides.",
  "One team from the first brief to the final report, supporting the ambitions of Saudi Vision 2030.": "Une seule équipe, du premier brief au rapport final, au service des ambitions de la Vision saoudienne 2030.", "We start with your objective, audience and budget, then shape the event concept around it.": "Nous partons de votre objectif, de votre public et de votre budget pour façonner le concept.", "Identity, stage design, content and show flow developed as one visual story.": "Identité, scénographie, contenu et déroulé sont conçus comme une seule histoire visuelle.", "Build, staging, lighting, sound and technology delivered by our own crews.": "Construction, scène, lumière, son et technologie sont réalisés par nos propres équipes.", "Logistics, hospitality, crowd flow and reporting on the day and after it.": "Logistique, accueil, gestion des flux et rapports pendant et après l’événement.",
  "Events and conferences management in the Kingdom of Saudi Arabia. We create exceptional impact.": "Gestion d’événements et de conférences en Arabie saoudite. Nous créons un impact exceptionnel.", "Kingdom of Saudi Arabia": "Royaume d’Arabie saoudite",
  "Shaping the future of the events industry in Saudi Arabia": "Façonner l’avenir de l’événementiel en Arabie saoudite", "Turning bold ideas into unforgettable experiences": "Transformer les idées audacieuses en expériences inoubliables", "Four principles behind every Litigon delivery": "Quatre principes au cœur de chaque réalisation Litigon", "Success partners": "Partenaires de réussite", "Successful events delivered": "Événements réalisés avec succès", "Operational & technical management hours": "Heures de gestion opérationnelle et technique", "Artists & influencers managed": "Artistes et influenceurs accompagnés", "Planning, development, execution and operations": "Planification, développement, exécution et opérations"
});

Object.assign(zh, {
  "Serving clients across": "服务范围遍及", "Saudi Arabia": "沙特阿拉伯", "Riyadh,": "利雅得，",
  "Litigon designs, produces and manages conferences, exhibitions and national celebrations across the Kingdom of Saudi Arabia — from the first idea to the final firework.": "Litigon 在沙特各地设计、制作和管理会议、展览及国家庆典，从最初构想到精彩收官。",
  "End-to-end management of conferences, exhibitions and corporate events: strategy, creative direction, production and on-site logistics.": "为会议、展览和企业活动提供端到端管理，包括战略、创意指导、制作和现场物流。",
  "Agenda design, speaker and delegation coordination, registration and hospitality for high-level summits.": "为高级别峰会提供议程设计、嘉宾与代表团协调、注册和接待服务。",
  "Interactive installations, smart registration and data-driven experiences that make every guest feel recognised.": "通过互动装置、智能注册和数据驱动体验，让每位来宾都感到备受重视。",
  "Campaign planning, content production and media coverage that build attendance before the doors open.": "通过营销策划、内容制作和媒体报道，在活动开始前吸引受众。",
  "Programming and operating cultural seasons, festivals and national celebrations for wide public audiences.": "为广大公众策划并运营文化季、节庆和国家庆典。",
  "Flow planning, access control and safety operations for venues of every scale.": "为各种规模场地提供人流规划、出入控制和安全运营。",
  "Protocol, reception and private hospitality for ministers, sponsors and official delegations.": "为部长、赞助商和官方代表团提供礼宾、接待及专属服务。",
  "Private Aviation": "私人航空", "Private jet arrangements, airport handling and ground transfers for guests and delegations.": "为来宾和代表团安排私人飞机、机场服务和地面接送。",
  "Drone shows, fireworks, stage design, lighting and sound engineered for one unforgettable moment.": "无人机表演、烟花、舞台设计、灯光和音响，共同打造难忘时刻。",
  "Choreographed drone formations that turn the night sky into your message.": "以编排精准的无人机阵列表演，让夜空传递您的讯息。", "Licensed pyrotechnic displays synchronised to music and stage moments.": "经许可的烟花特效，与音乐和舞台时刻精准同步。", "Smart registration, crowd analytics and interactive content driven by AI.": "由人工智能驱动的智能注册、人群分析和互动内容。", "Halls, stages, translation and hospitality built for high-level agendas.": "为高级别议程提供会场、舞台、翻译和接待服务。", "Protocol-trained hosts, lounges and transport for official delegations.": "为官方代表团提供专业礼宾人员、贵宾室和交通服务。", "Private jet charters, airport handling and seamless ground transfers.": "私人飞机包机、机场服务和无缝地面接送。",
  "One team from the first brief to the final report, supporting the ambitions of Saudi Vision 2030.": "从初次需求到最终报告，由一支团队全程负责，助力沙特 2030 愿景。", "We start with your objective, audience and budget, then shape the event concept around it.": "我们从您的目标、受众和预算出发，构建活动概念。", "Identity, stage design, content and show flow developed as one visual story.": "将品牌形象、舞台设计、内容和演出流程融为一个视觉故事。", "Build, staging, lighting, sound and technology delivered by our own crews.": "由自有团队完成搭建、舞台、灯光、音响和技术实施。", "Logistics, hospitality, crowd flow and reporting on the day and after it.": "负责活动当日及之后的物流、接待、人流和报告。",
  "Events and conferences management in the Kingdom of Saudi Arabia. We create exceptional impact.": "沙特阿拉伯王国的活动与会议管理专家。我们创造非凡影响力。", "Kingdom of Saudi Arabia": "沙特阿拉伯王国",
  "Shaping the future of the events industry in Saudi Arabia": "塑造沙特活动行业的未来", "Turning bold ideas into unforgettable experiences": "将大胆创意转化为难忘体验", "Four principles behind every Litigon delivery": "成就每个 Litigon 项目的四项原则", "Success partners": "成功合作伙伴", "Successful events delivered": "成功交付的活动", "Operational & technical management hours": "运营与技术管理小时", "Artists & influencers managed": "合作艺人与影响者", "Planning, development, execution and operations": "规划、开发、执行与运营"
});

Object.assign(ar, {
  "We create spectacular drone shows that transform the night sky into a living canvas. Every formation is designed around the occasion, combining precise choreography, light, music and storytelling to deliver a safe and unforgettable visual experience.": "نصنع عروض درون مبهرة تحوّل سماء الليل إلى لوحة حية. ويُصمم كل تشكيل بما يلائم المناسبة، جامعاً بين دقة الحركة والضوء والموسيقى والسرد لتقديم تجربة بصرية آمنة لا تُنسى.",
  "Our specialised teams design and produce fireworks and pyrotechnic shows for national celebrations, festivals and major events. Displays are planned with exact timing, creative direction and strict safety standards, then synchronised with music, lighting and live performances.": "تصمم فرقنا المتخصصة وتنتج عروض الألعاب النارية والمؤثرات للاحتفالات الوطنية والمهرجانات والفعاليات الكبرى. وتُخطط العروض بتوقيت دقيق وتوجيه إبداعي ومعايير سلامة صارمة، ثم تُزامن مع الموسيقى والإضاءة والعروض الحية.",
  "We integrate artificial intelligence into the guest journey through smart registration, facial recognition, crowd analytics and interactive experiences. These technologies help organisers understand attendance, improve movement and deliver personalised content in real time.": "ندمج الذكاء الاصطناعي في رحلة الضيف عبر التسجيل الذكي والتعرّف على الوجوه وتحليلات الحشود والتجارب التفاعلية. وتساعد هذه التقنيات المنظمين على فهم الحضور وتحسين الحركة وتقديم محتوى مخصص في الوقت الفعلي.",
  "We manage conferences and strategic summits from concept to closing session. Our work covers agenda development, speaker and delegation coordination, registration, staging, simultaneous interpretation, hospitality and complete on-site operations.": "ندير المؤتمرات والقمم الاستراتيجية من الفكرة حتى الجلسة الختامية. وتشمل أعمالنا تطوير جدول الأعمال وتنسيق المتحدثين والوفود والتسجيل وتجهيز المسرح والترجمة الفورية والضيافة وكامل العمليات الميدانية.",
  "We provide refined reception and hospitality services for VIP guests and official delegations. Protocol-trained teams coordinate arrivals, private lounges, transportation, accommodation and every detail of the guest journey with discretion and precision.": "نقدم خدمات استقبال وضيافة راقية لكبار الشخصيات والوفود الرسمية. وتنسق فرق مدربة على البروتوكول الوصول والصالات الخاصة والنقل والإقامة وكل تفاصيل رحلة الضيف بسرية ودقة.",
  "Our private aviation service arranges aircraft charter, flight coordination, airport handling and ground transportation. We provide a seamless, private and carefully managed travel experience for executives, VIP guests and official delegations.": "ترتب خدمة الطيران الخاص لدينا استئجار الطائرات وتنسيق الرحلات وخدمات المطارات والنقل الأرضي. ونوفر تجربة سفر سلسة وخاصة ومدارة بعناية للتنفيذيين وكبار الشخصيات والوفود الرسمية.",
  "To shape the future of the events and experiences industry in Saudi Arabia through innovation, operational excellence, and transformative experiences that set new international benchmarks.": "نسهم في رسم مستقبل صناعة الفعاليات والتجارب في المملكة العربية السعودية من خلال الابتكار والتميز التشغيلي وتجارب مؤثرة تضع معايير دولية جديدة.",
  "To transform bold ideas into unforgettable experiences through an integrated ecosystem of expertise, innovation, and strategic partnerships — creating measurable value for our clients while contributing to the ambitions of Saudi Vision 2030.": "نحوّل الأفكار الجريئة إلى تجارب لا تُنسى عبر منظومة متكاملة من الخبرات والابتكار والشراكات الاستراتيجية، لنصنع قيمة قابلة للقياس لعملائنا ونسهم في تحقيق طموحات رؤية السعودية 2030.",
  "Litigon in every detail": "ليتغون في كل تفصيل", "A consistent presence from planning to production": "حضور متسق من التخطيط إلى الإنتاج",
  "Our identity carries through every touchpoint, from the planning desk and team credentials to the people delivering safely on site.": "تحضر هويتنا في كل نقطة تواصل، من مكتب التخطيط وبطاقات الفريق إلى الكوادر التي تنفذ العمل بأمان في الموقع.",
  "Our integrated operational and media ecosystem seamlessly connects strategy, creativity, production, logistics, and execution into one unified workflow — ensuring every event is delivered with precision, efficiency, and measurable impact.": "تربط منظومتنا التشغيلية والإعلامية المتكاملة الاستراتيجية والإبداع والإنتاج والخدمات اللوجستية والتنفيذ ضمن مسار عمل موحد، لضمان تقديم كل فعالية بدقة وكفاءة وأثر قابل للقياس.",
  "We create innovative concepts and digital solutions that give every event its own distinctive identity, ensuring meaningful audience engagement and leaving a lasting impact.": "نبتكر مفاهيم وحلولاً رقمية تمنح كل فعالية هويتها المميزة، وتحقق تفاعلاً حقيقياً مع الجمهور وأثراً مستداماً.",
  "We are committed to the highest international standards in crowd management, time control, and risk management, ensuring that every event and conference is delivered with exceptional precision, efficiency, and professionalism.": "نلتزم بأعلى المعايير الدولية في إدارة الحشود والوقت والمخاطر، لضمان تنفيذ كل فعالية ومؤتمر بدقة وكفاءة واحترافية استثنائية.",
  "We stand as a trusted strategic partner, capable of delivering major national events and flagship projects while transforming our partners' ambitions into measurable success and lasting achievements.": "نقف شريكاً استراتيجياً موثوقاً قادراً على تنفيذ الفعاليات الوطنية الكبرى والمشاريع الرائدة، وتحويل طموحات شركائنا إلى نجاح قابل للقياس وإنجازات مستدامة.",
  "We deliver integrated solutions in event management and live experiences, covering planning, development, execution, and operations through a comprehensive portfolio of specialized services.": "نقدم حلولاً متكاملة في إدارة الفعاليات والتجارب الحية، تشمل التخطيط والتطوير والتنفيذ والتشغيل عبر محفظة شاملة من الخدمات المتخصصة.",
  "Conferences, exhibitions, sports weekends and national celebrations delivered across the Kingdom.": "مؤتمرات ومعارض وفعاليات رياضية واحتفالات وطنية نُفذت في أنحاء المملكة.",
  "Riyad Bank main stage": "المسرح الرئيسي لبنك الرياض", "Corporate conference": "مؤتمر شركات", "Stage design, screens and full technical production for a national bank event.": "تصميم المسرح والشاشات والإنتاج التقني الكامل لفعالية بنك وطني.",
  "Saudi pavilion": "الجناح السعودي", Exhibition: "معرض", "Pavilion concept, build and hosting team for an international exhibition.": "تصميم وبناء الجناح وتوفير فريق الضيافة لمعرض دولي.",
  "Formula 1 activation": "فعالية فورمولا 1", "Sports hospitality": "ضيافة رياضية", "Brand activation and guest experience around a Formula 1 race weekend.": "تنشيط للعلامة وتجربة ضيوف خلال عطلة سباق فورمولا 1.",
  "Paddock Club hospitality": "ضيافة نادي البادوك", "VIP hospitality": "ضيافة كبار الشخصيات", "VIP lounge design, catering coordination and guest management.": "تصميم صالة كبار الشخصيات وتنسيق خدمات الطعام وإدارة الضيوف.",
  "Air show": "عرض جوي", "Public show": "عرض جماهيري", "Aerial display programming with crowd management and live commentary.": "برمجة عرض جوي مع إدارة الحشود والتعليق المباشر.",
  "Desert rally": "رالي الصحراء", Motorsport: "رياضة المحركات", "Route logistics, hospitality camps and safety operations in the desert.": "لوجستيات المسار ومخيمات الضيافة وعمليات السلامة في الصحراء.",
  "Security forces exhibition booth": "جناح معرض القوات الأمنية", "Government exhibition": "معرض حكومي", "Interactive booth featuring drone technology and live demonstrations.": "جناح تفاعلي يعرض تقنية الدرون وعروضاً حية.",
  "Ajlan & Bros booth": "جناح عجلان وإخوانه", "Exhibition stand": "جناح معرض", "Custom stand design and build for a leading Saudi group.": "تصميم وبناء جناح مخصص لمجموعة سعودية رائدة.",
  "Healthcare event": "فعالية صحية", "Exhibition presence and visitor experience for a medical brand.": "حضور في المعرض وتجربة زوار لعلامة طبية.",
  "STC Play zone": "منطقة STC Play", "Brand activation": "تنشيط علامة تجارية", "Gaming and entertainment activation with a fully themed environment.": "فعالية ألعاب وترفيه ضمن بيئة متكاملة الهوية.",
  "Lazadak stand": "جناح لازاداك", "Retail-style stand with product display and hosting staff.": "جناح بطابع تجزئة مع عرض المنتجات وطاقم ضيافة.",
  "Cultural season village": "قرية الموسم الثقافي", "Cultural season": "موسم ثقافي", "Multi-booth village with lighting design and evening programming.": "قرية متعددة الأجنحة مع تصميم إضاءة وبرنامج مسائي.",
  "Padel activation": "فعالية البادل", "Sports activation": "تنشيط رياضي", "Sponsored padel court activation with audience entertainment.": "فعالية ملعب بادل برعاية مع ترفيه للجمهور.",
  "Litigon is an events and conferences management company in Saudi Arabia. We handle strategy, creative direction, technical production, hospitality and on-site operations for conferences, exhibitions, cultural seasons, sports weekends and national celebrations.": "ليتغون شركة سعودية لإدارة الفعاليات والمؤتمرات، نتولى الاستراتيجية والتوجيه الإبداعي والإنتاج التقني والضيافة والعمليات الميدانية للمؤتمرات والمعارض والمواسم الثقافية والفعاليات الرياضية والاحتفالات الوطنية.",
  "The earlier the better. Large conferences and cultural seasons usually need two to six months of preparation, while smaller activations and exhibition stands can be delivered in a few weeks. Tell us your date and we will tell you honestly what is possible.": "كلما كان التواصل أبكر كان أفضل. تحتاج المؤتمرات الكبرى والمواسم الثقافية عادةً إلى شهرين حتى ستة أشهر من التحضير، بينما يمكن تنفيذ الفعاليات الصغيرة وأجنحة المعارض خلال أسابيع. شاركونا الموعد وسنوضح لكم بصراحة ما يمكن تنفيذه.",
  "Both. Many clients ask us to run the event end to end, while others bring us in for a specific element such as stage production, an exhibition stand, crowd management or VIP reception.": "كلاهما. يطلب منا كثير من العملاء إدارة الفعالية بالكامل، بينما يستعين بنا آخرون لعنصر محدد مثل إنتاج المسرح أو جناح معرض أو إدارة الحشود أو استقبال كبار الشخصيات.",
  "Yes. Our protocol-trained hosts manage reception, lounges, transport and private aviation arrangements for ministers, sponsors and official delegations.": "نعم. يدير مضيفونا المدربون على البروتوكول الاستقبال والصالات والنقل وترتيبات الطيران الخاص للوزراء والرعاة والوفود الرسمية.",
  "Yes. We produce choreographed drone formations and licensed pyrotechnic displays synchronised with music, stage moments and screen content.": "نعم. ننتج تشكيلات درون مصممة وعروضاً نارية مرخصة ومتزامنة مع الموسيقى ولحظات المسرح ومحتوى الشاشات.",
  "We work across the Kingdom of Saudi Arabia, with teams and suppliers able to mobilise for events in any region, including remote desert locations.": "نعمل في جميع أنحاء المملكة العربية السعودية، مع فرق وموردين قادرين على التحرك للفعاليات في أي منطقة، بما فيها المواقع الصحراوية النائية.",
  "Every event is quoted individually based on scale, venue, production requirements and duration. After an initial conversation we send a detailed proposal with a clear breakdown.": "يُسعّر كل حدث بشكل مستقل وفق الحجم والموقع ومتطلبات الإنتاج والمدة. وبعد المحادثة الأولية نرسل عرضاً مفصلاً ببنود واضحة.",
  "Yes. Much of our work supports national and cultural programmes tied to Saudi Vision 2030, from public seasons to international pavilions.": "نعم. يدعم جزء كبير من أعمالنا البرامج الوطنية والثقافية المرتبطة برؤية السعودية 2030، من المواسم الجماهيرية إلى الأجنحة الدولية.",
  "Failed to send message": "تعذر إرسال الرسالة", "Please try again later or contact us directly.": "يرجى المحاولة لاحقاً أو التواصل معنا مباشرة.", "Failed to send message. Please try again later.": "تعذر إرسال الرسالة. يرجى المحاولة لاحقاً.", "Message sent successfully! We'll get back to you soon.": "تم إرسال الرسالة بنجاح! سنتواصل معك قريباً."
});

Object.assign(fr, {
  "We create spectacular drone shows that transform the night sky into a living canvas. Every formation is designed around the occasion, combining precise choreography, light, music and storytelling to deliver a safe and unforgettable visual experience.": "Nous créons des spectacles de drones qui transforment le ciel nocturne en toile vivante. Chaque formation est conçue pour l’occasion et associe chorégraphie précise, lumière, musique et narration pour offrir une expérience visuelle sûre et inoubliable.",
  "Our specialised teams design and produce fireworks and pyrotechnic shows for national celebrations, festivals and major events. Displays are planned with exact timing, creative direction and strict safety standards, then synchronised with music, lighting and live performances.": "Nos équipes spécialisées conçoivent et produisent des spectacles pyrotechniques pour les célébrations nationales, festivals et grands événements. Chaque séquence suit un minutage précis, une direction créative et des normes de sécurité strictes, puis se synchronise avec la musique, la lumière et les performances en direct.",
  "We integrate artificial intelligence into the guest journey through smart registration, facial recognition, crowd analytics and interactive experiences. These technologies help organisers understand attendance, improve movement and deliver personalised content in real time.": "Nous intégrons l’intelligence artificielle au parcours des invités grâce à l’inscription intelligente, la reconnaissance faciale, l’analyse des foules et des expériences interactives. Ces technologies aident les organisateurs à comprendre la fréquentation, fluidifier les déplacements et diffuser du contenu personnalisé en temps réel.",
  "We manage conferences and strategic summits from concept to closing session. Our work covers agenda development, speaker and delegation coordination, registration, staging, simultaneous interpretation, hospitality and complete on-site operations.": "Nous gérons les conférences et sommets stratégiques, du concept à la séance de clôture. Notre mission couvre l’élaboration du programme, la coordination des intervenants et délégations, les inscriptions, la scénographie, l’interprétation simultanée, l’accueil et l’ensemble des opérations sur site.",
  "We provide refined reception and hospitality services for VIP guests and official delegations. Protocol-trained teams coordinate arrivals, private lounges, transportation, accommodation and every detail of the guest journey with discretion and precision.": "Nous proposons des services d’accueil haut de gamme aux VIP et délégations officielles. Nos équipes formées au protocole coordonnent les arrivées, salons privés, transports, hébergements et chaque détail du parcours avec discrétion et précision.",
  "Our private aviation service arranges aircraft charter, flight coordination, airport handling and ground transportation. We provide a seamless, private and carefully managed travel experience for executives, VIP guests and official delegations.": "Notre service d’aviation privée organise l’affrètement, la coordination des vols, l’assistance aéroportuaire et les transports terrestres. Nous offrons aux dirigeants, VIP et délégations officielles une expérience de voyage fluide, privée et soigneusement gérée.",
  "To shape the future of the events and experiences industry in Saudi Arabia through innovation, operational excellence, and transformative experiences that set new international benchmarks.": "Façonner l’avenir du secteur des événements et des expériences en Arabie saoudite grâce à l’innovation, l’excellence opérationnelle et des expériences transformatrices qui établissent de nouvelles références internationales.",
  "To transform bold ideas into unforgettable experiences through an integrated ecosystem of expertise, innovation, and strategic partnerships — creating measurable value for our clients while contributing to the ambitions of Saudi Vision 2030.": "Transformer les idées audacieuses en expériences inoubliables grâce à un écosystème intégré d’expertise, d’innovation et de partenariats stratégiques, créant une valeur mesurable pour nos clients tout en contribuant aux ambitions de la Vision saoudienne 2030.",
  "Litigon in every detail": "Litigon dans chaque détail", "A consistent presence from planning to production": "Une présence cohérente, de la planification à la production",
  "Our identity carries through every touchpoint, from the planning desk and team credentials to the people delivering safely on site.": "Notre identité s’exprime à chaque point de contact, du bureau de planification et des accréditations jusqu’aux équipes qui assurent une exécution sûre sur site.",
  "Our integrated operational and media ecosystem seamlessly connects strategy, creativity, production, logistics, and execution into one unified workflow — ensuring every event is delivered with precision, efficiency, and measurable impact.": "Notre écosystème opérationnel et médiatique intégré relie stratégie, création, production, logistique et exécution dans un flux unifié, afin que chaque événement soit réalisé avec précision, efficacité et impact mesurable.",
  "We create innovative concepts and digital solutions that give every event its own distinctive identity, ensuring meaningful audience engagement and leaving a lasting impact.": "Nous créons des concepts innovants et des solutions numériques qui donnent à chaque événement une identité distinctive, favorisent un engagement pertinent du public et laissent une empreinte durable.",
  "We are committed to the highest international standards in crowd management, time control, and risk management, ensuring that every event and conference is delivered with exceptional precision, efficiency, and professionalism.": "Nous respectons les normes internationales les plus exigeantes en matière de gestion des foules, des délais et des risques, afin que chaque événement soit livré avec une précision, une efficacité et un professionnalisme exceptionnels.",
  "We stand as a trusted strategic partner, capable of delivering major national events and flagship projects while transforming our partners' ambitions into measurable success and lasting achievements.": "Partenaire stratégique de confiance, nous réalisons de grands événements nationaux et projets emblématiques tout en transformant les ambitions de nos partenaires en réussites mesurables et durables.",
  "We deliver integrated solutions in event management and live experiences, covering planning, development, execution, and operations through a comprehensive portfolio of specialized services.": "Nous proposons des solutions intégrées de gestion événementielle et d’expériences en direct, couvrant la planification, le développement, l’exécution et les opérations grâce à un portefeuille complet de services spécialisés.",
  "Conferences, exhibitions, sports weekends and national celebrations delivered across the Kingdom.": "Conférences, expositions, week-ends sportifs et célébrations nationales réalisés dans tout le Royaume.",
  "Riyad Bank main stage": "Scène principale de Riyad Bank", "Corporate conference": "Conférence d’entreprise", "Stage design, screens and full technical production for a national bank event.": "Scénographie, écrans et production technique complète pour l’événement d’une banque nationale.",
  "Saudi pavilion": "Pavillon saoudien", Exhibition: "Exposition", "Pavilion concept, build and hosting team for an international exhibition.": "Conception et construction du pavillon, avec équipe d’accueil pour une exposition internationale.",
  "Formula 1 activation": "Activation Formule 1", "Sports hospitality": "Hospitalité sportive", "Brand activation and guest experience around a Formula 1 race weekend.": "Activation de marque et expérience invités pendant un week-end de Formule 1.",
  "Paddock Club hospitality": "Hospitalité Paddock Club", "VIP hospitality": "Hospitalité VIP", "VIP lounge design, catering coordination and guest management.": "Conception du salon VIP, coordination de la restauration et gestion des invités.",
  "Air show": "Spectacle aérien", "Public show": "Spectacle public", "Aerial display programming with crowd management and live commentary.": "Programmation du spectacle aérien, gestion des foules et commentaires en direct.",
  "Desert rally": "Rallye du désert", Motorsport: "Sport automobile", "Route logistics, hospitality camps and safety operations in the desert.": "Logistique du parcours, camps d’accueil et opérations de sécurité dans le désert.",
  "Security forces exhibition booth": "Stand des forces de sécurité", "Government exhibition": "Exposition gouvernementale", "Interactive booth featuring drone technology and live demonstrations.": "Stand interactif présentant la technologie des drones et des démonstrations en direct.",
  "Ajlan & Bros booth": "Stand Ajlan & Bros", "Exhibition stand": "Stand d’exposition", "Custom stand design and build for a leading Saudi group.": "Conception et construction sur mesure pour un grand groupe saoudien.",
  "Healthcare event": "Événement de santé", "Exhibition presence and visitor experience for a medical brand.": "Présence d’exposition et expérience visiteurs pour une marque médicale.",
  "STC Play zone": "Zone STC Play", "Brand activation": "Activation de marque", "Gaming and entertainment activation with a fully themed environment.": "Activation gaming et divertissement dans un univers entièrement scénographié.",
  "Lazadak stand": "Stand Lazadak", "Retail-style stand with product display and hosting staff.": "Stand inspiré du commerce de détail avec présentation des produits et équipe d’accueil.",
  "Cultural season village": "Village de saison culturelle", "Cultural season": "Saison culturelle", "Multi-booth village with lighting design and evening programming.": "Village à plusieurs stands avec conception lumière et programmation en soirée.",
  "Padel activation": "Activation padel", "Sports activation": "Activation sportive", "Sponsored padel court activation with audience entertainment.": "Activation sponsorisée autour d’un terrain de padel avec animations pour le public.",
  "Litigon is an events and conferences management company in Saudi Arabia. We handle strategy, creative direction, technical production, hospitality and on-site operations for conferences, exhibitions, cultural seasons, sports weekends and national celebrations.": "Litigon est une société saoudienne de gestion d’événements et de conférences. Nous assurons la stratégie, la direction créative, la production technique, l’accueil et les opérations sur site pour les conférences, expositions, saisons culturelles, événements sportifs et célébrations nationales.",
  "The earlier the better. Large conferences and cultural seasons usually need two to six months of preparation, while smaller activations and exhibition stands can be delivered in a few weeks. Tell us your date and we will tell you honestly what is possible.": "Le plus tôt sera le mieux. Les grandes conférences et saisons culturelles demandent généralement deux à six mois de préparation, tandis que les petites activations et stands peuvent être réalisés en quelques semaines. Donnez-nous votre date et nous vous indiquerons clairement ce qui est possible.",
  "Both. Many clients ask us to run the event end to end, while others bring us in for a specific element such as stage production, an exhibition stand, crowd management or VIP reception.": "Les deux. De nombreux clients nous confient l’événement de bout en bout, tandis que d’autres font appel à nous pour un élément précis : production scénique, stand d’exposition, gestion des foules ou accueil VIP.",
  "Yes. Our protocol-trained hosts manage reception, lounges, transport and private aviation arrangements for ministers, sponsors and official delegations.": "Oui. Nos hôtes formés au protocole gèrent l’accueil, les salons, le transport et les dispositions d’aviation privée pour les ministres, sponsors et délégations officielles.",
  "Yes. We produce choreographed drone formations and licensed pyrotechnic displays synchronised with music, stage moments and screen content.": "Oui. Nous produisons des formations de drones chorégraphiées et des spectacles pyrotechniques autorisés, synchronisés avec la musique, les séquences scéniques et les contenus d’écran.",
  "We work across the Kingdom of Saudi Arabia, with teams and suppliers able to mobilise for events in any region, including remote desert locations.": "Nous intervenons dans tout le Royaume d’Arabie saoudite, avec des équipes et fournisseurs mobilisables dans toutes les régions, y compris les sites désertiques isolés.",
  "Every event is quoted individually based on scale, venue, production requirements and duration. After an initial conversation we send a detailed proposal with a clear breakdown.": "Chaque événement fait l’objet d’un devis adapté à son ampleur, au lieu, aux besoins de production et à la durée. Après un premier échange, nous envoyons une proposition détaillée et clairement ventilée.",
  "Yes. Much of our work supports national and cultural programmes tied to Saudi Vision 2030, from public seasons to international pavilions.": "Oui. Une grande partie de notre travail soutient les programmes nationaux et culturels liés à la Vision saoudienne 2030, des saisons publiques aux pavillons internationaux.",
  "Failed to send message": "Échec de l’envoi du message", "Please try again later or contact us directly.": "Veuillez réessayer plus tard ou nous contacter directement.", "Failed to send message. Please try again later.": "Échec de l’envoi du message. Veuillez réessayer plus tard.", "Message sent successfully! We'll get back to you soon.": "Message envoyé ! Nous vous répondrons bientôt."
});

Object.assign(zh, {
  "We create spectacular drone shows that transform the night sky into a living canvas. Every formation is designed around the occasion, combining precise choreography, light, music and storytelling to deliver a safe and unforgettable visual experience.": "我们打造震撼的无人机表演，将夜空化为灵动的画布。每个编队都围绕活动主题设计，融合精准编排、灯光、音乐与叙事，呈现安全而难忘的视觉体验。",
  "Our specialised teams design and produce fireworks and pyrotechnic shows for national celebrations, festivals and major events. Displays are planned with exact timing, creative direction and strict safety standards, then synchronised with music, lighting and live performances.": "我们的专业团队为国家庆典、节日和大型活动设计制作烟花与特效表演。每场演出都经过精准计时、创意指导和严格安全规划，并与音乐、灯光及现场演出同步。",
  "We integrate artificial intelligence into the guest journey through smart registration, facial recognition, crowd analytics and interactive experiences. These technologies help organisers understand attendance, improve movement and deliver personalised content in real time.": "我们通过智能注册、人脸识别、人群分析和互动体验，将人工智能融入宾客旅程。这些技术帮助主办方了解出席情况、优化人流，并实时提供个性化内容。",
  "We manage conferences and strategic summits from concept to closing session. Our work covers agenda development, speaker and delegation coordination, registration, staging, simultaneous interpretation, hospitality and complete on-site operations.": "我们从概念策划到闭幕环节全程管理会议与战略峰会，涵盖议程制定、演讲嘉宾与代表团协调、注册、舞台、同声传译、接待及完整现场运营。",
  "We provide refined reception and hospitality services for VIP guests and official delegations. Protocol-trained teams coordinate arrivals, private lounges, transportation, accommodation and every detail of the guest journey with discretion and precision.": "我们为贵宾和官方代表团提供高规格接待服务。受过礼宾培训的团队以审慎和精准的方式协调抵达、私人休息室、交通、住宿及宾客旅程的每个细节。",
  "Our private aviation service arranges aircraft charter, flight coordination, airport handling and ground transportation. We provide a seamless, private and carefully managed travel experience for executives, VIP guests and official delegations.": "我们的私人航空服务安排飞机包租、航班协调、机场服务和地面交通，为高管、贵宾和官方代表团提供顺畅、私密且精心管理的出行体验。",
  "To shape the future of the events and experiences industry in Saudi Arabia through innovation, operational excellence, and transformative experiences that set new international benchmarks.": "以创新、卓越运营和具有变革力的体验塑造沙特活动与体验行业的未来，树立新的国际标杆。",
  "To transform bold ideas into unforgettable experiences through an integrated ecosystem of expertise, innovation, and strategic partnerships — creating measurable value for our clients while contributing to the ambitions of Saudi Vision 2030.": "通过专业能力、创新和战略伙伴关系组成的一体化生态，将大胆创意转化为难忘体验，为客户创造可衡量的价值，并助力沙特 2030 愿景。",
  "Litigon in every detail": "每个细节中的 Litigon", "A consistent presence from planning to production": "从规划到制作始终如一的品牌呈现",
  "Our identity carries through every touchpoint, from the planning desk and team credentials to the people delivering safely on site.": "从策划工作台和团队证件到现场安全执行人员，我们的品牌形象贯穿每个接触点。",
  "Our integrated operational and media ecosystem seamlessly connects strategy, creativity, production, logistics, and execution into one unified workflow — ensuring every event is delivered with precision, efficiency, and measurable impact.": "我们的一体化运营与媒体生态将战略、创意、制作、物流和执行无缝连接为统一流程，确保每场活动都以精准、高效且可衡量的影响力交付。",
  "We create innovative concepts and digital solutions that give every event its own distinctive identity, ensuring meaningful audience engagement and leaving a lasting impact.": "我们打造创新概念与数字解决方案，为每场活动赋予独特身份，促进有意义的受众互动并留下持久影响。",
  "We are committed to the highest international standards in crowd management, time control, and risk management, ensuring that every event and conference is delivered with exceptional precision, efficiency, and professionalism.": "我们坚持人群、时间与风险管理的最高国际标准，确保每场活动和会议都以卓越的精准度、效率和专业水准交付。",
  "We stand as a trusted strategic partner, capable of delivering major national events and flagship projects while transforming our partners' ambitions into measurable success and lasting achievements.": "作为值得信赖的战略伙伴，我们能够交付重大国家活动和旗舰项目，并将合作伙伴的愿景转化为可衡量的成功与长久成果。",
  "We deliver integrated solutions in event management and live experiences, covering planning, development, execution, and operations through a comprehensive portfolio of specialized services.": "我们通过全面的专业服务组合，提供涵盖规划、开发、执行和运营的活动管理与现场体验一体化解决方案。",
  "Conferences, exhibitions, sports weekends and national celebrations delivered across the Kingdom.": "在沙特全国交付会议、展览、体育周末和国家庆典。",
  "Riyad Bank main stage": "利雅得银行主舞台", "Corporate conference": "企业会议", "Stage design, screens and full technical production for a national bank event.": "为全国性银行活动提供舞台设计、屏幕和完整技术制作。",
  "Saudi pavilion": "沙特展馆", Exhibition: "展览", "Pavilion concept, build and hosting team for an international exhibition.": "为国际展览提供展馆概念、搭建和接待团队。",
  "Formula 1 activation": "一级方程式主题活动", "Sports hospitality": "体育接待", "Brand activation and guest experience around a Formula 1 race weekend.": "围绕一级方程式比赛周末打造品牌活动与宾客体验。",
  "Paddock Club hospitality": "围场俱乐部接待", "VIP hospitality": "贵宾接待", "VIP lounge design, catering coordination and guest management.": "贵宾休息室设计、餐饮协调和宾客管理。",
  "Air show": "航空表演", "Public show": "公众表演", "Aerial display programming with crowd management and live commentary.": "航空表演编排，并配合人群管理和现场解说。",
  "Desert rally": "沙漠拉力赛", Motorsport: "赛车运动", "Route logistics, hospitality camps and safety operations in the desert.": "沙漠中的路线物流、接待营地和安全运营。",
  "Security forces exhibition booth": "安全部队展台", "Government exhibition": "政府展览", "Interactive booth featuring drone technology and live demonstrations.": "展示无人机技术和现场演示的互动展台。",
  "Ajlan & Bros booth": "Ajlan & Bros 展台", "Exhibition stand": "展台", "Custom stand design and build for a leading Saudi group.": "为沙特领先集团定制设计和搭建展台。",
  "Healthcare event": "医疗活动", "Exhibition presence and visitor experience for a medical brand.": "为医疗品牌打造展览呈现和访客体验。",
  "STC Play zone": "STC Play 区域", "Brand activation": "品牌活动", "Gaming and entertainment activation with a fully themed environment.": "在完整主题环境中开展游戏娱乐活动。",
  "Lazadak stand": "Lazadak 展台", "Retail-style stand with product display and hosting staff.": "零售风格展台，配备产品展示和接待人员。",
  "Cultural season village": "文化季村落", "Cultural season": "文化季", "Multi-booth village with lighting design and evening programming.": "由多个展位组成的村落，配合灯光设计与夜间节目。",
  "Padel activation": "板式网球主题活动", "Sports activation": "体育主题活动", "Sponsored padel court activation with audience entertainment.": "赞助板式网球场活动，并配套观众娱乐内容。",
  "Litigon is an events and conferences management company in Saudi Arabia. We handle strategy, creative direction, technical production, hospitality and on-site operations for conferences, exhibitions, cultural seasons, sports weekends and national celebrations.": "Litigon 是一家位于沙特的活动与会议管理公司，为会议、展览、文化季、体育周末和国家庆典提供战略、创意指导、技术制作、接待和现场运营。",
  "The earlier the better. Large conferences and cultural seasons usually need two to six months of preparation, while smaller activations and exhibition stands can be delivered in a few weeks. Tell us your date and we will tell you honestly what is possible.": "越早联系越好。大型会议和文化季通常需要两到六个月准备，小型主题活动和展台则可在数周内完成。告诉我们日期，我们会坦诚说明可行方案。",
  "Both. Many clients ask us to run the event end to end, while others bring us in for a specific element such as stage production, an exhibition stand, crowd management or VIP reception.": "两种方式都可以。许多客户委托我们端到端运营整场活动，也有客户邀请我们负责舞台制作、展台、人群管理或贵宾接待等具体环节。",
  "Yes. Our protocol-trained hosts manage reception, lounges, transport and private aviation arrangements for ministers, sponsors and official delegations.": "可以。受过礼宾培训的接待人员为部长、赞助商和官方代表团管理接待、休息室、交通及私人航空安排。",
  "Yes. We produce choreographed drone formations and licensed pyrotechnic displays synchronised with music, stage moments and screen content.": "可以。我们制作编排精准的无人机阵列表演和经许可的烟花特效，并与音乐、舞台环节和屏幕内容同步。",
  "We work across the Kingdom of Saudi Arabia, with teams and suppliers able to mobilise for events in any region, including remote desert locations.": "我们的服务遍及沙特全国，团队和供应商可前往任何地区执行活动，包括偏远沙漠地点。",
  "Every event is quoted individually based on scale, venue, production requirements and duration. After an initial conversation we send a detailed proposal with a clear breakdown.": "每场活动会根据规模、场地、制作要求和时长单独报价。初步沟通后，我们会发送明细清晰的详细方案。",
  "Yes. Much of our work supports national and cultural programmes tied to Saudi Vision 2030, from public seasons to international pavilions.": "可以。我们许多项目服务于与沙特 2030 愿景相关的国家及文化计划，从公众文化季到国际展馆。",
  "Failed to send message": "消息发送失败", "Please try again later or contact us directly.": "请稍后重试或直接联系我们。", "Failed to send message. Please try again later.": "消息发送失败，请稍后重试。", "Message sent successfully! We'll get back to you soon.": "消息发送成功！我们会尽快回复您。"
});

Object.assign(ar, {
  "Cookie Policy": "سياسة ملفات تعريف الارتباط", "The latest": "الأحدث", "Stories, ideas and company news": "قصص وأفكار وأخبار الشركة", All: "الكل", "Filter articles by category": "تصفية المقالات حسب الفئة", "Featured stories": "قصص مميزة", "No stories are available in this category yet.": "لا توجد قصص متاحة في هذه الفئة حالياً.",
  "Expand": "توسيع", "Collapse": "طي", "Head Office": "المكتب الرئيسي", "Google Maps": "خرائط Google", "Open in Google Maps": "فتح في خرائط Google", "View head office on Google Maps": "عرض المكتب الرئيسي على خرائط Google", "Litigon head office map": "خريطة المكتب الرئيسي لليتغون", "Riyadh, 5660 Anas Ibn Malik st., Al Malqa Dist., P.O. Box 13525": "الرياض، شارع أنس بن مالك 5660، حي الملقا، ص.ب 13525",
  "Inside the planning of a large-scale Saudi event": "داخل كواليس التخطيط لفعالية سعودية كبرى", "How technology turns a live show into a shared moment": "كيف تحول التقنية العرض الحي إلى لحظة مشتركة", "Designing exhibition spaces that invite conversation": "تصميم مساحات عرض تشجع على الحوار", "Five details that elevate executive conferences": "خمسة تفاصيل ترتقي بالمؤتمرات التنفيذية", "From first sketch to opening night": "من الرسم الأول إلى ليلة الافتتاح", "Creating cultural experiences with a sense of place": "صناعة تجارب ثقافية بروح المكان",
  "Behind the scenes": "خلف الكواليس", Exhibitions: "المعارض", Conferences: "المؤتمرات", "Project stories": "قصص المشاريع", "Cultural events": "فعاليات ثقافية", "Litigon Editorial Team": "فريق تحرير ليتغون", "6 min read": "قراءة 6 دقائق", "5 min read": "قراءة 5 دقائق", "4 min read": "قراءة 4 دقائق", "7 min read": "قراءة 7 دقائق",
  "September 8, 2026": "8 سبتمبر 2026", "August 24, 2026": "24 أغسطس 2026", "August 10, 2026": "10 أغسطس 2026", "July 28, 2026": "28 يوليو 2026", "July 14, 2026": "14 يوليو 2026", "June 30, 2026": "30 يونيو 2026",
  "Built around the guest experience": "مصمم حول تجربة الضيف", "Every Litigon project starts with the audience journey. We connect planning, production and on-site operations so every touchpoint feels intentional and every team works from the same plan.": "يبدأ كل مشروع في ليتغون من رحلة الجمهور. نربط التخطيط والإنتاج والعمليات الميدانية لتكون كل نقطة تواصل مقصودة وتعمل جميع الفرق وفق خطة واحدة.", "What makes the difference": "ما الذي يصنع الفارق", "From the first concept through final delivery, our team combines local knowledge with disciplined execution to create memorable experiences across Saudi Arabia.": "من الفكرة الأولى حتى التسليم النهائي، يجمع فريقنا المعرفة المحلية بالتنفيذ المنضبط لصناعة تجارب لا تُنسى في أنحاء المملكة العربية السعودية.",
  "Large events look effortless only when months of detailed planning are working quietly in the background.": "تبدو الفعاليات الكبرى سلسة فقط عندما تعمل أشهر من التخطيط الدقيق بهدوء خلف الكواليس.", "One integrated production schedule": "جدول إنتاج متكامل واحد", "Clear ownership across every supplier": "مسؤوليات واضحة لدى كل مورد", "Guest-flow testing before opening day": "اختبار حركة الضيوف قبل يوم الافتتاح",
  "Lighting, sound, drones and special effects are most powerful when they serve one clear creative idea.": "تبلغ الإضاءة والصوت والدرون والمؤثرات الخاصة أقصى تأثيرها عندما تخدم فكرة إبداعية واحدة واضحة.", "Technology selected for the story": "تقنية مختارة لخدمة القصة", "Precise rehearsals and safety checks": "بروفات دقيقة وفحوصات سلامة", "A single show-control workflow": "مسار موحد للتحكم بالعرض",
  "A successful exhibition stand does more than attract attention—it makes the next interaction feel natural.": "يتجاوز جناح المعرض الناجح جذب الانتباه، فهو يجعل التفاعل التالي طبيعياً.", "A strong visual idea visible from a distance": "فكرة بصرية قوية تُرى من بعيد", "Intuitive visitor circulation": "حركة زوار بديهية", "Flexible spaces for meetings and demonstrations": "مساحات مرنة للاجتماعات والعروض",
  "For senior audiences, confidence comes from the details: effortless arrivals, crisp content and hospitality that never interrupts the programme.": "بالنسبة للجمهور التنفيذي، تأتي الثقة من التفاصيل: وصول سلس ومحتوى واضح وضيافة لا تقاطع البرنامج.", "A simple registration journey": "رحلة تسجيل بسيطة", "Speaker-ready technical production": "إنتاج تقني جاهز للمتحدثين", "Hospitality timed around the agenda": "ضيافة منسقة مع جدول الأعمال",
  "Turning a creative concept into a live environment takes hundreds of coordinated decisions across design, build and operations.": "يتطلب تحويل المفهوم الإبداعي إلى بيئة حية مئات القرارات المنسقة بين التصميم والبناء والتشغيل.", "Concepts grounded in practical delivery": "مفاهيم مبنية على تنفيذ عملي", "Early coordination between creative and technical teams": "تنسيق مبكر بين الفرق الإبداعية والتقنية", "Real-time decisions on site": "قرارات فورية في الموقع",
  "The strongest cultural events feel unmistakably connected to their setting while remaining welcoming to every visitor.": "ترتبط أقوى الفعاليات الثقافية بمكانها بوضوح مع بقائها مرحبة بكل زائر.", "Local stories treated with care": "قصص محلية تُروى بعناية", "Contemporary formats that widen access": "صيغ معاصرة توسع الوصول", "Operations designed for comfort and flow": "عمليات مصممة للراحة والانسيابية",
  "Get insights delivered straight to you": "تصلك الأفكار مباشرة", "Get the latest Litigon news and event insights.": "احصل على أحدث أخبار ليتغون ورؤى الفعاليات.", "Stay updated with Litigon": "ابقَ على اطلاع مع ليتغون", "Your email": "بريدك الإلكتروني", Subscribe: "اشترك", "Email address": "عنوان البريد الإلكتروني", "Successfully subscribed!": "تم الاشتراك بنجاح!", "Explore more from the Litigon newsroom": "اكتشف المزيد من غرفة أخبار ليتغون",
  "Page not found": "الصفحة غير موجودة", "This page missed its cue.": "هذه الصفحة فاتتها الإشارة.", "The address may be incorrect, or the page may have moved while we were setting the stage.": "قد يكون العنوان غير صحيح، أو ربما انتقلت الصفحة أثناء تجهيزنا للمشهد.", "Return home": "العودة للرئيسية", "Explore projects": "استكشف المشاريع", "The show goes on · Litigon, Riyadh": "العرض مستمر · ليتغون، الرياض",
  "First name must be at least 2 characters": "يجب ألا يقل الاسم الأول عن حرفين", "Last name must be at least 2 characters": "يجب ألا يقل اسم العائلة عن حرفين", "Please enter a valid email address": "يرجى إدخال بريد إلكتروني صحيح", "Please enter a valid phone number": "يرجى إدخال رقم هاتف صحيح", "Subject must be at least 3 characters": "يجب ألا يقل الموضوع عن 3 أحرف", "Message must be at least 10 characters": "يجب ألا تقل الرسالة عن 10 أحرف"
});

Object.assign(fr, {
  "Cookie Policy": "Politique relative aux cookies", "The latest": "Les dernières actualités", "Stories, ideas and company news": "Histoires, idées et actualités de l’entreprise", All: "Tout", "Filter articles by category": "Filtrer les articles par catégorie", "Featured stories": "Articles à la une", "No stories are available in this category yet.": "Aucun article n’est encore disponible dans cette catégorie.",
  "Expand": "Développer", "Collapse": "Réduire", "Head Office": "Siège social", "Google Maps": "Google Maps", "Open in Google Maps": "Ouvrir dans Google Maps", "View head office on Google Maps": "Voir le siège social sur Google Maps", "Litigon head office map": "Carte du siège social de Litigon", "Riyadh, 5660 Anas Ibn Malik st., Al Malqa Dist., P.O. Box 13525": "Riyad, 5660 rue Anas Ibn Malik, quartier Al Malqa, B.P. 13525",
  "Inside the planning of a large-scale Saudi event": "Dans les coulisses de la planification d’un grand événement saoudien", "How technology turns a live show into a shared moment": "Comment la technologie transforme un spectacle en moment partagé", "Designing exhibition spaces that invite conversation": "Concevoir des espaces d’exposition propices aux échanges", "Five details that elevate executive conferences": "Cinq détails qui subliment les conférences de dirigeants", "From first sketch to opening night": "Du premier croquis à la soirée d’ouverture", "Creating cultural experiences with a sense of place": "Créer des expériences culturelles ancrées dans leur lieu",
  "Behind the scenes": "Dans les coulisses", Exhibitions: "Expositions", Conferences: "Conférences", "Project stories": "Histoires de projets", "Cultural events": "Événements culturels", "Litigon Editorial Team": "Équipe éditoriale Litigon", "6 min read": "6 min de lecture", "5 min read": "5 min de lecture", "4 min read": "4 min de lecture", "7 min read": "7 min de lecture",
  "September 8, 2026": "8 septembre 2026", "August 24, 2026": "24 août 2026", "August 10, 2026": "10 août 2026", "July 28, 2026": "28 juillet 2026", "July 14, 2026": "14 juillet 2026", "June 30, 2026": "30 juin 2026",
  "Built around the guest experience": "Conçu autour de l’expérience invité", "Every Litigon project starts with the audience journey. We connect planning, production and on-site operations so every touchpoint feels intentional and every team works from the same plan.": "Chaque projet Litigon commence par le parcours du public. Nous relions planification, production et opérations sur site afin que chaque point de contact soit intentionnel et que toutes les équipes suivent le même plan.", "What makes the difference": "Ce qui fait la différence", "From the first concept through final delivery, our team combines local knowledge with disciplined execution to create memorable experiences across Saudi Arabia.": "Du premier concept à la livraison finale, notre équipe associe connaissance locale et exécution rigoureuse pour créer des expériences mémorables dans toute l’Arabie saoudite.",
  "Large events look effortless only when months of detailed planning are working quietly in the background.": "Les grands événements semblent fluides uniquement lorsque des mois de planification détaillée œuvrent discrètement en coulisses.", "One integrated production schedule": "Un calendrier de production intégré", "Clear ownership across every supplier": "Des responsabilités claires pour chaque fournisseur", "Guest-flow testing before opening day": "Tests des flux visiteurs avant l’ouverture",
  "Lighting, sound, drones and special effects are most powerful when they serve one clear creative idea.": "La lumière, le son, les drones et les effets spéciaux sont les plus puissants lorsqu’ils servent une idée créative claire.", "Technology selected for the story": "Une technologie choisie au service du récit", "Precise rehearsals and safety checks": "Répétitions précises et contrôles de sécurité", "A single show-control workflow": "Un flux unique de contrôle du spectacle",
  "A successful exhibition stand does more than attract attention—it makes the next interaction feel natural.": "Un stand réussi ne se contente pas d’attirer l’attention : il rend l’échange suivant naturel.", "A strong visual idea visible from a distance": "Une idée visuelle forte, visible de loin", "Intuitive visitor circulation": "Une circulation intuitive des visiteurs", "Flexible spaces for meetings and demonstrations": "Des espaces flexibles pour réunions et démonstrations",
  "For senior audiences, confidence comes from the details: effortless arrivals, crisp content and hospitality that never interrupts the programme.": "Pour un public de dirigeants, la confiance naît des détails : arrivées fluides, contenu précis et accueil qui ne perturbe jamais le programme.", "A simple registration journey": "Un parcours d’inscription simple", "Speaker-ready technical production": "Une production technique prête pour les intervenants", "Hospitality timed around the agenda": "Un accueil rythmé par le programme",
  "Turning a creative concept into a live environment takes hundreds of coordinated decisions across design, build and operations.": "Transformer un concept créatif en environnement réel exige des centaines de décisions coordonnées entre conception, construction et opérations.", "Concepts grounded in practical delivery": "Des concepts ancrés dans une réalisation concrète", "Early coordination between creative and technical teams": "Une coordination précoce des équipes créatives et techniques", "Real-time decisions on site": "Des décisions en temps réel sur site",
  "The strongest cultural events feel unmistakably connected to their setting while remaining welcoming to every visitor.": "Les événements culturels les plus forts sont profondément liés à leur cadre tout en restant accueillants pour chaque visiteur.", "Local stories treated with care": "Des histoires locales traitées avec soin", "Contemporary formats that widen access": "Des formats contemporains qui élargissent l’accès", "Operations designed for comfort and flow": "Des opérations pensées pour le confort et la fluidité",
  "Get insights delivered straight to you": "Recevez nos analyses directement", "Get the latest Litigon news and event insights.": "Recevez les dernières actualités Litigon et nos analyses événementielles.", "Stay updated with Litigon": "Suivez l’actualité de Litigon", "Your email": "Votre e-mail", Subscribe: "S’abonner", "Email address": "Adresse e-mail", "Successfully subscribed!": "Inscription réussie !", "Explore more from the Litigon newsroom": "Découvrez plus d’articles de la rédaction Litigon",
  "Page not found": "Page introuvable", "This page missed its cue.": "Cette page a manqué son entrée.", "The address may be incorrect, or the page may have moved while we were setting the stage.": "L’adresse est peut-être incorrecte, ou la page a été déplacée pendant nos préparatifs.", "Return home": "Retour à l’accueil", "Explore projects": "Découvrir les projets", "The show goes on · Litigon, Riyadh": "Le spectacle continue · Litigon, Riyad",
  "First name must be at least 2 characters": "Le prénom doit comporter au moins 2 caractères", "Last name must be at least 2 characters": "Le nom doit comporter au moins 2 caractères", "Please enter a valid email address": "Veuillez saisir une adresse e-mail valide", "Please enter a valid phone number": "Veuillez saisir un numéro de téléphone valide", "Subject must be at least 3 characters": "L’objet doit comporter au moins 3 caractères", "Message must be at least 10 characters": "Le message doit comporter au moins 10 caractères"
});

Object.assign(zh, {
  "Cookie Policy": "Cookie 政策", "The latest": "最新内容", "Stories, ideas and company news": "故事、观点与公司动态", All: "全部", "Filter articles by category": "按类别筛选文章", "Featured stories": "精选文章", "No stories are available in this category yet.": "此类别暂时没有文章。",
  "Expand": "展开", "Collapse": "收起", "Head Office": "总部", "Google Maps": "Google 地图", "Open in Google Maps": "在 Google 地图中打开", "View head office on Google Maps": "在 Google 地图中查看总部", "Litigon head office map": "Litigon 总部地图", "Riyadh, 5660 Anas Ibn Malik st., Al Malqa Dist., P.O. Box 13525": "利雅得，Anas Ibn Malik 街 5660 号，Al Malqa 区，邮政信箱 13525",
  "Inside the planning of a large-scale Saudi event": "沙特大型活动策划幕后", "How technology turns a live show into a shared moment": "技术如何将现场演出变成共同记忆", "Designing exhibition spaces that invite conversation": "设计促进交流的展览空间", "Five details that elevate executive conferences": "提升高管会议体验的五个细节", "From first sketch to opening night": "从第一张草图到开幕之夜", "Creating cultural experiences with a sense of place": "打造富有地域感的文化体验",
  "Behind the scenes": "幕后故事", Exhibitions: "展览", Conferences: "会议", "Project stories": "项目故事", "Cultural events": "文化活动", "Litigon Editorial Team": "Litigon 编辑团队", "6 min read": "阅读 6 分钟", "5 min read": "阅读 5 分钟", "4 min read": "阅读 4 分钟", "7 min read": "阅读 7 分钟",
  "September 8, 2026": "2026年9月8日", "August 24, 2026": "2026年8月24日", "August 10, 2026": "2026年8月10日", "July 28, 2026": "2026年7月28日", "July 14, 2026": "2026年7月14日", "June 30, 2026": "2026年6月30日",
  "Built around the guest experience": "围绕宾客体验打造", "Every Litigon project starts with the audience journey. We connect planning, production and on-site operations so every touchpoint feels intentional and every team works from the same plan.": "每个 Litigon 项目都从受众旅程出发。我们连接策划、制作和现场运营，让每个接触点都经过用心设计，让所有团队遵循同一份计划。", "What makes the difference": "成就差异的关键", "From the first concept through final delivery, our team combines local knowledge with disciplined execution to create memorable experiences across Saudi Arabia.": "从最初概念到最终交付，我们的团队将本地经验与严谨执行相结合，在沙特各地创造难忘体验。",
  "Large events look effortless only when months of detailed planning are working quietly in the background.": "大型活动之所以显得从容顺畅，是因为数月的细致规划在幕后持续运转。", "One integrated production schedule": "一份一体化制作时间表", "Clear ownership across every supplier": "每家供应商职责清晰", "Guest-flow testing before opening day": "开幕前测试宾客动线",
  "Lighting, sound, drones and special effects are most powerful when they serve one clear creative idea.": "灯光、音响、无人机和特效围绕一个清晰创意服务时，最具感染力。", "Technology selected for the story": "为叙事选择合适技术", "Precise rehearsals and safety checks": "精准彩排与安全检查", "A single show-control workflow": "统一的演出控制流程",
  "A successful exhibition stand does more than attract attention—it makes the next interaction feel natural.": "成功的展台不只吸引目光，也让接下来的交流自然发生。", "A strong visual idea visible from a distance": "远处即可识别的强烈视觉概念", "Intuitive visitor circulation": "直观的访客动线", "Flexible spaces for meetings and demonstrations": "适合会议和演示的灵活空间",
  "For senior audiences, confidence comes from the details: effortless arrivals, crisp content and hospitality that never interrupts the programme.": "面对高层受众，信任来自细节：顺畅抵达、清晰内容，以及不打断议程的接待服务。", "A simple registration journey": "简洁的注册流程", "Speaker-ready technical production": "随时支持演讲嘉宾的技术制作", "Hospitality timed around the agenda": "与议程精准配合的接待",
  "Turning a creative concept into a live environment takes hundreds of coordinated decisions across design, build and operations.": "将创意概念变成真实环境，需要在设计、搭建和运营之间协调数百项决策。", "Concepts grounded in practical delivery": "以实际交付为基础的概念", "Early coordination between creative and technical teams": "创意与技术团队尽早协同", "Real-time decisions on site": "现场实时决策",
  "The strongest cultural events feel unmistakably connected to their setting while remaining welcoming to every visitor.": "最出色的文化活动与所在地紧密相连，同时让每位访客都感到宾至如归。", "Local stories treated with care": "用心呈现本地故事", "Contemporary formats that widen access": "扩大参与范围的当代表达", "Operations designed for comfort and flow": "为舒适与顺畅而设计的运营",
  "Get insights delivered straight to you": "让洞察直达您的邮箱", "Get the latest Litigon news and event insights.": "获取最新 Litigon 动态与活动洞察。", "Stay updated with Litigon": "关注 Litigon 最新动态", "Your email": "您的电子邮箱", Subscribe: "订阅", "Email address": "电子邮箱地址", "Successfully subscribed!": "订阅成功！", "Explore more from the Litigon newsroom": "探索更多 Litigon 新闻室内容",
  "Page not found": "页面未找到", "This page missed its cue.": "这个页面错过了登场时机。", "The address may be incorrect, or the page may have moved while we were setting the stage.": "地址可能有误，或页面在我们布置舞台时已被移动。", "Return home": "返回首页", "Explore projects": "探索项目", "The show goes on · Litigon, Riyadh": "精彩继续 · Litigon，利雅得",
  "First name must be at least 2 characters": "名字至少需要 2 个字符", "Last name must be at least 2 characters": "姓氏至少需要 2 个字符", "Please enter a valid email address": "请输入有效的电子邮箱地址", "Please enter a valid phone number": "请输入有效的电话号码", "Subject must be at least 3 characters": "主题至少需要 3 个字符", "Message must be at least 10 characters": "留言至少需要 10 个字符"
});

const dictionaries: Record<Locale, Dictionary> = { en: {}, ar, fr, zh };
const STORAGE_KEY = "litigon-language";
const normalizeArabicBrandName = (value: string, dictionary: Dictionary) =>
  dictionary === ar ? value.replace(/ليتغون|ليتيقون|ليتيحون/g, "ليتيجون") : value;

interface LanguageContextValue {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (source: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);
const textSources = new WeakMap<Text, string>();
const attributeSources = new WeakMap<Element, Record<string, string>>();

const translateTextNode = (node: Text, dictionary: Dictionary) => {
  const parent = node.parentElement;
  if (!parent || parent.closest("[data-i18n-ignore]")) return;
  const source = textSources.get(node) ?? node.nodeValue ?? "";
  if (!textSources.has(node)) textSources.set(node, source);
  const trimmed = source.trim();
  const translated = dictionary[trimmed];
  const next = translated
    ? source.replace(trimmed, normalizeArabicBrandName(translated, dictionary))
    : source;
  if (node.nodeValue !== next) node.nodeValue = next;
};

const translateTree = (root: ParentNode, dictionary: Dictionary) => {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  let current = walker.nextNode();
  while (current) {
    const parent = current.parentElement;
    if (parent && !parent.closest("[data-i18n-ignore]") && !["SCRIPT", "STYLE", "NOSCRIPT"].includes(parent.tagName)) {
      translateTextNode(current as Text, dictionary);
    }
    current = walker.nextNode();
  }
  root.querySelectorAll?.("[placeholder], [aria-label], [title], [content], img[alt]").forEach((element) => {
    if (element.closest("[data-i18n-ignore]")) return;
    const stored = attributeSources.get(element) ?? {};
    ["placeholder", "aria-label", "title", "alt", "content"].forEach((attribute) => {
      const value = element.getAttribute(attribute);
      if (value !== null && stored[attribute] === undefined) stored[attribute] = value;
      const source = stored[attribute];
      if (source !== undefined) {
        const translated = dictionary[source] ?? source;
        element.setAttribute(attribute, normalizeArabicBrandName(translated, dictionary));
      }
    });
    attributeSources.set(element, stored);
  });
};

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [locale, setLocaleState] = useState<Locale>(() => {
    const stored = localStorage.getItem(STORAGE_KEY);
    return stored === "ar" || stored === "fr" || stored === "zh" ? stored : "en";
  });
  const setLocale = useCallback((next: Locale) => {
    localStorage.setItem(STORAGE_KEY, next);
    setLocaleState(next);
  }, []);
  const t = useCallback(
    (source: string) => normalizeArabicBrandName(dictionaries[locale][source] ?? source, dictionaries[locale]),
    [locale],
  );

  useEffect(() => {
    const html = document.documentElement;
    html.lang = locale === "zh" ? "zh-Hans" : locale;
    html.dir = locale === "ar" ? "rtl" : "ltr";
    const dictionary = dictionaries[locale];
    translateTree(document, dictionary);
    const observer = new MutationObserver((mutations) => {
      mutations.forEach((mutation) => {
        if (mutation.type === "characterData") translateTextNode(mutation.target as Text, dictionary);
        mutation.addedNodes.forEach((node) => {
          if (node.nodeType === Node.TEXT_NODE) translateTextNode(node as Text, dictionary);
          else if (node.nodeType === Node.ELEMENT_NODE) translateTree(node as Element, dictionary);
        });
      });
    });
    observer.observe(document.documentElement, { childList: true, subtree: true, characterData: true });
    return () => observer.disconnect();
  }, [locale]);

  const value = useMemo(() => ({ locale, setLocale, t }), [locale, setLocale, t]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
